image: demurgos/cpp:insa-gcc-5

before_script:
 - git submodule update --init --recursive

stages:
  - build
  - test

build-all:
  stage: build
  script:
    - make
#  artifacts:
#    untracked: true

gl_test:
  stage: test
  script:
    - make prepare
    - make test.unit
    - make test.memory
    - make test.end-to-end
